const WORD_PAIRS = [
    // ========== ФРУКТЫ И ЯГОДЫ ==========
    { civilian: "Арбуз", spy: "Дыня" },
    { civilian: "Банан", spy: "Киви" },
    { civilian: "Яблоко", spy: "Груша" },
    { civilian: "Апельсин", spy: "Мандарин" },
    { civilian: "Лимон", spy: "Лайм" },
    { civilian: "Персик", spy: "Абрикос" },
    { civilian: "Клубника", spy: "Малина" },
    { civilian: "Виноград", spy: "Смородина" },
    { civilian: "Черешня", spy: "Вишня" },
    { civilian: "Слива", spy: "Чернослив" },
    { civilian: "Гранат", spy: "Инжир" },
    { civilian: "Хурма", spy: "Манго" },
    { civilian: "Ананас", spy: "Папайя" },
    { civilian: "Кокос", spy: "Авокадо" },
    { civilian: "Голубика", spy: "Черника" },
    { civilian: "Ежевика", spy: "Шелковица" },
    { civilian: "Крыжовник", spy: "Киви" },
    { civilian: "Брусника", spy: "Клюква" },
    { civilian: "Калина", spy: "Рябина" },
    { civilian: "Облепиха", spy: "Морошка" },
    { civilian: "Изюм", spy: "Курага" },
    { civilian: "Чернослив", spy: "Урюк" },
    { civilian: "Цукат", spy: "Мармелад" },
    { civilian: "Джем", spy: "Повидло" },
    { civilian: "Компот", spy: "Морс" },
    { civilian: "Сок", spy: "Нектар" },
    { civilian: "Смузи", spy: "Коктейль" },
    { civilian: "Сорбет", spy: "Мороженое" },
    { civilian: "Йогурт", spy: "Кефир" },
    { civilian: "Творог", spy: "Сыр" },
    { civilian: "Сметана", spy: "Сливки" },
    { civilian: "Масло", spy: "Маргарин" },
    { civilian: "Мёд", spy: "Варенье" },
    { civilian: "Сгущёнка", spy: "Карамель" },
    { civilian: "Шоколад", spy: "Конфета" },
    { civilian: "Миндаль", spy: "Арахис" },
    { civilian: "Фундук", spy: "Кешью" },
    { civilian: "Грецкий орех", spy: "Кедровый орех" },
    { civilian: "Фисташка", spy: "Арахис" },
    { civilian: "Каштан", spy: "Жёлудь" },

    // ========== ОВОЩИ И ЗЕЛЕНЬ ==========
    { civilian: "Помидор", spy: "Перец" },
    { civilian: "Огурец", spy: "Кабачок" },
    { civilian: "Морковь", spy: "Свёкла" },
    { civilian: "Картофель", spy: "Батат" },
    { civilian: "Лук", spy: "Чеснок" },
    { civilian: "Капуста", spy: "Салат" },
    { civilian: "Брокколи", spy: "Цветная капуста" },
    { civilian: "Репа", spy: "Редька" },
    { civilian: "Тыква", spy: "Патиссон" },
    { civilian: "Баклажан", spy: "Кабачок" },
    { civilian: "Фасоль", spy: "Горох" },
    { civilian: "Чечевица", spy: "Нут" },
    { civilian: "Кукуруза", spy: "Горох" },
    { civilian: "Спаржа", spy: "Сельдерей" },
    { civilian: "Шпинат", spy: "Щавель" },
    { civilian: "Петрушка", spy: "Укроп" },
    { civilian: "Базилик", spy: "Кинза" },
    { civilian: "Имбирь", spy: "Хрен" },
    { civilian: "Дайкон", spy: "Редис" },
    { civilian: "Лук-порей", spy: "Зелёный лук" },
    { civilian: "Красный лук", spy: "Репчатый лук" },
    { civilian: "Тимьян", spy: "Розмарин" },
    { civilian: "Мята", spy: "Мелисса" },
    { civilian: "Лавровый лист", spy: "Розмарин" },
    { civilian: "Корица", spy: "Гвоздика" },
    { civilian: "Куркума", spy: "Шафран" },
    { civilian: "Паприка", spy: "Чили" },
    { civilian: "Чёрный перец", spy: "Душистый перец" },
    { civilian: "Красный перец", spy: "Чили" },
    { civilian: "Ваниль", spy: "Миндаль" },
    { civilian: "Тмин", spy: "Укроп" },
    { civilian: "Кунжут", spy: "Мак" },

    // ========== ЕДА И БЛЮДА ==========
    { civilian: "Пицца", spy: "Бургер" },
    { civilian: "Суши", spy: "Роллы" },
    { civilian: "Пельмени", spy: "Вареники" },
    { civilian: "Хлеб", spy: "Батон" },
    { civilian: "Сыр", spy: "Творог" },
    { civilian: "Кофе", spy: "Какао" },
    { civilian: "Чай", spy: "Компот" },
    { civilian: "Борщ", spy: "Щи" },
    { civilian: "Суп", spy: "Бульон" },
    { civilian: "Каша", spy: "Пюре" },
    { civilian: "Макароны", spy: "Спагетти" },
    { civilian: "Блины", spy: "Оладьи" },
    { civilian: "Сырники", spy: "Творожники" },
    { civilian: "Плов", spy: "Ризотто" },
    { civilian: "Шашлык", spy: "Гриль" },
    { civilian: "Котлета", spy: "Тефтеля" },
    { civilian: "Голубцы", spy: "Долма" },
    { civilian: "Окрошка", spy: "Свекольник" },
    { civilian: "Винегрет", spy: "Оливье" },
    { civilian: "Пирог", spy: "Пирожок" },
    { civilian: "Торт", spy: "Пирожное" },
    { civilian: "Мороженое", spy: "Сорбет" },
    { civilian: "Шоколад", spy: "Конфета" },
    { civilian: "Мёд", spy: "Варенье" },
    { civilian: "Йогурт", spy: "Кефир" },
    { civilian: "Сметана", spy: "Сливки" },
    { civilian: "Масло", spy: "Маргарин" },
    { civilian: "Колбаса", spy: "Сосиски" },
    { civilian: "Бекон", spy: "Ветчина" },
    { civilian: "Круассан", spy: "Булочка" },
    { civilian: "Хачапури", spy: "Лаваш" },
    { civilian: "Чебурек", spy: "Беляш" },
    { civilian: "Шаурма", spy: "Буррито" },
    { civilian: "Тако", spy: "Кесадилья" },
    { civilian: "Лапша", spy: "Макароны" },
    { civilian: "Солянка", spy: "Харчо" },
    { civilian: "Рассольник", spy: "Свекольник" },
    { civilian: "Томатный суп", spy: "Борщ" },
    { civilian: "Крем-суп", spy: "Суп-пюре" },
    { civilian: "Хумус", spy: "Паштет" },
    { civilian: "Омлет", spy: "Яичница" },
    { civilian: "Глазунья", spy: "Болтунья" },
    { civilian: "Багет", spy: "Чиабатта" },
    { civilian: "Лаваш", spy: "Тортилья" },
    { civilian: "Гренки", spy: "Сухарики" },
    { civilian: "Сэндвич", spy: "Бутерброд" },
    { civilian: "Гамбургер", spy: "Чизбургер" },
    { civilian: "Чизкейк", spy: "Тирамису" },
    { civilian: "Маффин", spy: "Капкейк" },
    { civilian: "Брауни", spy: "Торт" },
    { civilian: "Печенье", spy: "Пряники" },
    { civilian: "Вафли", spy: "Гофры" },
    { civilian: "Пончики", spy: "Пирожное" },
    { civilian: "Штрудель", spy: "Пирог" },
    { civilian: "Эклер", spy: "Профитроль" },
    { civilian: "Зефир", spy: "Пастила" },
    { civilian: "Мармелад", spy: "Желе" },
    { civilian: "Пудинг", spy: "Суфле" },
    { civilian: "Кисель", spy: "Мусс" },
    { civilian: "Безе", spy: "Меренга" },
    { civilian: "Халва", spy: "Нуга" },
    { civilian: "Мюсли", spy: "Гранола" },
    { civilian: "Овсянка", spy: "Каша" },
    { civilian: "Гречка", spy: "Рис" },
    { civilian: "Пшено", spy: "Перловка" },
    { civilian: "Манка", spy: "Кускус" },
    { civilian: "Картофель фри", spy: "Картофель по-деревенски" },

    // ========== НАПИТКИ ==========
    { civilian: "Сок", spy: "Нектар" },
    { civilian: "Молоко", spy: "Кефир" },
    { civilian: "Квас", spy: "Лимонад" },
    { civilian: "Лимонад", spy: "Газировка" },
    { civilian: "Кисель", spy: "Морс" },
    { civilian: "Капучино", spy: "Латте" },
    { civilian: "Эспрессо", spy: "Американо" },
    { civilian: "Коктейль", spy: "Смузи" },
    { civilian: "Чай", spy: "Матча" },
    { civilian: "Каркаде", spy: "Чай" },
    { civilian: "Айран", spy: "Тан" },
    { civilian: "Какао", spy: "Горячий шоколад" },
    { civilian: "Компот", spy: "Узвар" },

    // ========== ЖИВОТНЫЕ ==========
    { civilian: "Собака", spy: "Волк" },
    { civilian: "Кошка", spy: "Рысь" },
    { civilian: "Лев", spy: "Тигр" },
    { civilian: "Лиса", spy: "Песец" },
    { civilian: "Заяц", spy: "Кролик" },
    { civilian: "Слон", spy: "Бегемот" },
    { civilian: "Пингвин", spy: "Гагарка" },
    { civilian: "Лошадь", spy: "Пони" },
    { civilian: "Осёл", spy: "Мул" },
    { civilian: "Корова", spy: "Бык" },
    { civilian: "Коза", spy: "Овца" },
    { civilian: "Свинья", spy: "Кабан" },
    { civilian: "Курица", spy: "Индюк" },
    { civilian: "Утка", spy: "Гусь" },
    { civilian: "Орёл", spy: "Сокол" },
    { civilian: "Ястреб", spy: "Коршун" },
    { civilian: "Ворона", spy: "Грач" },
    { civilian: "Голубь", spy: "Воробей" },
    { civilian: "Синица", spy: "Снегирь" },
    { civilian: "Ласточка", spy: "Стриж" },
    { civilian: "Сова", spy: "Филин" },
    { civilian: "Змея", spy: "Удав" },
    { civilian: "Ящерица", spy: "Саламандра" },
    { civilian: "Лягушка", spy: "Жаба" },
    { civilian: "Крокодил", spy: "Аллигатор" },
    { civilian: "Черепаха", spy: "Броненосец" },
    { civilian: "Кит", spy: "Кашалот" },
    { civilian: "Дельфин", spy: "Косатка" },
    { civilian: "Акула", spy: "Скат" },
    { civilian: "Осьминог", spy: "Кальмар" },
    { civilian: "Краб", spy: "Рак" },
    { civilian: "Креветка", spy: "Лангуст" },
    { civilian: "Улитка", spy: "Слизень" },
    { civilian: "Паук", spy: "Скорпион" },
    { civilian: "Муравей", spy: "Термит" },
    { civilian: "Пчела", spy: "Оса" },
    { civilian: "Шмель", spy: "Шершень" },
    { civilian: "Бабочка", spy: "Мотылёк" },
    { civilian: "Комар", spy: "Москит" },
    { civilian: "Стрекоза", spy: "Кузнечик" },
    { civilian: "Жук", spy: "Таракан" },
    { civilian: "Божья коровка", spy: "Колорадский жук" },
    { civilian: "Светлячок", spy: "Сверчок" },
    { civilian: "Муха", spy: "Овод" },
    { civilian: "Моль", spy: "Бабочка" },
    { civilian: "Дождевой червь", spy: "Пиявка" },
    { civilian: "Гусеница", spy: "Сороконожка" },
    { civilian: "Ёж", spy: "Дикобраз" },
    { civilian: "Барсук", spy: "Енот" },
    { civilian: "Выдра", spy: "Норка" },
    { civilian: "Бобр", spy: "Ондатра" },
    { civilian: "Хомяк", spy: "Морская свинка" },
    { civilian: "Крыса", spy: "Мышь" },
    { civilian: "Белка", spy: "Бурундук" },
    { civilian: "Суслик", spy: "Хомяк" },
    { civilian: "Шиншилла", spy: "Дегу" },
    { civilian: "Куница", spy: "Соболь" },
    { civilian: "Хорёк", spy: "Норка" },
    { civilian: "Кенгуру", spy: "Валлаби" },
    { civilian: "Коала", spy: "Вомбат" },
    { civilian: "Панда", spy: "Енот" },
    { civilian: "Бурый медведь", spy: "Белый медведь" },
    { civilian: "Пума", spy: "Рысь" },
    { civilian: "Гепард", spy: "Леопард" },
    { civilian: "Пантера", spy: "Ягуар" },
    { civilian: "Леопард", spy: "Гепард" },
    { civilian: "Рысь", spy: "Каракал" },
    { civilian: "Гиена", spy: "Волк" },
    { civilian: "Шакал", spy: "Койот" },
    { civilian: "Песец", spy: "Лиса" },
    { civilian: "Олень", spy: "Лось" },
    { civilian: "Косуля", spy: "Олень" },
    { civilian: "Антилопа", spy: "Газель" },
    { civilian: "Зебра", spy: "Лошадь" },
    { civilian: "Жираф", spy: "Окапи" },
    { civilian: "Носорог", spy: "Бегемот" },
    { civilian: "Капибара", spy: "Бобр" },
    { civilian: "Лама", spy: "Альпака" },
    { civilian: "Верблюд", spy: "Лошадь" },
    { civilian: "Бизон", spy: "Буйвол" },
    { civilian: "Морж", spy: "Тюлень" },
    { civilian: "Морской лев", spy: "Морской котик" },
    { civilian: "Белуха", spy: "Дельфин" },
    { civilian: "Игуана", spy: "Варан" },
    { civilian: "Геккон", spy: "Хамелеон" },
    { civilian: "Анаконда", spy: "Питон" },
    { civilian: "Кобра", spy: "Гадюка" },
    { civilian: "Уж", spy: "Полоз" },
    { civilian: "Хамелеон", spy: "Ящерица" },
    { civilian: "Тритон", spy: "Саламандра" },
    { civilian: "Лягушка", spy: "Жаба" },
    { civilian: "Пиранья", spy: "Акула" },
    { civilian: "Щука", spy: "Судак" },
    { civilian: "Окунь", spy: "Ёрш" },
    { civilian: "Карась", spy: "Карп" },
    { civilian: "Лещ", spy: "Плотва" },
    { civilian: "Сазан", spy: "Карп" },
    { civilian: "Форель", spy: "Лосось" },
    { civilian: "Сёмга", spy: "Горбуша" },
    { civilian: "Тунец", spy: "Скумбрия" },
    { civilian: "Сельдь", spy: "Сардина" },
    { civilian: "Треска", spy: "Пикша" },
    { civilian: "Минтай", spy: "Хек" },
    { civilian: "Камбала", spy: "Палтус" },
    { civilian: "Сом", spy: "Налим" },
    { civilian: "Осётр", spy: "Стерлядь" },
    { civilian: "Золотая рыбка", spy: "Гуппи" },
    { civilian: "Скалярия", spy: "Гуппи" },
    { civilian: "Петушок", spy: "Гурами" },

    // ========== ПТИЦЫ ==========
    { civilian: "Орёл", spy: "Сокол" },
    { civilian: "Ястреб", spy: "Коршун" },
    { civilian: "Ворона", spy: "Грач" },
    { civilian: "Голубь", spy: "Воробей" },
    { civilian: "Синица", spy: "Снегирь" },
    { civilian: "Ласточка", spy: "Стриж" },
    { civilian: "Сова", spy: "Филин" },
    { civilian: "Курица", spy: "Индюк" },
    { civilian: "Утка", spy: "Гусь" },
    { civilian: "Лебедь", spy: "Гусь" },
    { civilian: "Журавль", spy: "Аист" },
    { civilian: "Цапля", spy: "Журавль" },
    { civilian: "Фламинго", spy: "Цапля" },
    { civilian: "Пеликан", spy: "Аист" },
    { civilian: "Чайка", spy: "Альбатрос" },
    { civilian: "Тукан", spy: "Попугай" },
    { civilian: "Ара", spy: "Какаду" },
    { civilian: "Волнистый попугай", spy: "Неразлучник" },
    { civilian: "Канарейка", spy: "Щегол" },
    { civilian: "Зяблик", spy: "Воробей" },
    { civilian: "Скворец", spy: "Дрозд" },
    { civilian: "Соловей", spy: "Дрозд" },
    { civilian: "Жаворонок", spy: "Соловей" },
    { civilian: "Иволга", spy: "Синица" },
    { civilian: "Дятел", spy: "Поползень" },
    { civilian: "Кукушка", spy: "Сорока" },
    { civilian: "Сорока", spy: "Ворона" },
    { civilian: "Галка", spy: "Ворона" },
    { civilian: "Сойка", spy: "Сорока" },
    { civilian: "Клёст", spy: "Снегирь" },
    { civilian: "Свиристель", spy: "Снегирь" },
    { civilian: "Зимородок", spy: "Синица" },
    { civilian: "Удод", spy: "Дятел" },
    { civilian: "Стриж", spy: "Ласточка" },
    { civilian: "Беркут", spy: "Орёл" },
    { civilian: "Сапсан", spy: "Сокол" },
    { civilian: "Гриф", spy: "Кондор" },
    { civilian: "Колибри", spy: "Попугай" },
    { civilian: "Страус", spy: "Эму" },

    // ========== ПРОФЕССИИ ==========
    { civilian: "Врач", spy: "Ветеринар" },
    { civilian: "Повар", spy: "Кондитер" },
    { civilian: "Учитель", spy: "Профессор" },
    { civilian: "Полицейский", spy: "Военный" },
    { civilian: "Пожарный", spy: "Спасатель" },
    { civilian: "Художник", spy: "Дизайнер" },
    { civilian: "Музыкант", spy: "Композитор" },
    { civilian: "Актёр", spy: "Режиссёр" },
    { civilian: "Писатель", spy: "Поэт" },
    { civilian: "Журналист", spy: "Репортёр" },
    { civilian: "Фотограф", spy: "Оператор" },
    { civilian: "Строитель", spy: "Архитектор" },
    { civilian: "Пилот", spy: "Космонавт" },
    { civilian: "Моряк", spy: "Рыбак" },
    { civilian: "Швея", spy: "Модельер" },
    { civilian: "Парикмахер", spy: "Визажист" },
    { civilian: "Массажист", spy: "Физиотерапевт" },
    { civilian: "Психолог", spy: "Психиатр" },
    { civilian: "Хирург", spy: "Травматолог" },
    { civilian: "Терапевт", spy: "Педиатр" },
    { civilian: "Стоматолог", spy: "Ортодонт" },
    { civilian: "Окулист", spy: "Офтальмолог" },
    { civilian: "Лор", spy: "Отоларинголог" },
    { civilian: "Кардиолог", spy: "Невролог" },
    { civilian: "Дерматолог", spy: "Косметолог" },
    { civilian: "Адвокат", spy: "Прокурор" },
    { civilian: "Судья", spy: "Адвокат" },
    { civilian: "Нотариус", spy: "Юрист" },
    { civilian: "Бухгалтер", spy: "Экономист" },
    { civilian: "Финансист", spy: "Банкир" },
    { civilian: "Программист", spy: "Системный администратор" },
    { civilian: "Тестировщик", spy: "Программист" },
    { civilian: "Веб-дизайнер", spy: "Графический дизайнер" },
    { civilian: "Переводчик", spy: "Лингвист" },
    { civilian: "Историк", spy: "Археолог" },
    { civilian: "Геолог", spy: "Археолог" },
    { civilian: "Эколог", spy: "Биолог" },
    { civilian: "Химик", spy: "Физик" },
    { civilian: "Математик", spy: "Физик" },
    { civilian: "Инженер", spy: "Конструктор" },
    { civilian: "Механик", spy: "Инженер" },
    { civilian: "Электрик", spy: "Сантехник" },
    { civilian: "Сварщик", spy: "Токарь" },
    { civilian: "Плотник", spy: "Столяр" },
    { civilian: "Каменщик", spy: "Штукатур" },
    { civilian: "Маляр", spy: "Штукатур" },
    { civilian: "Крановщик", spy: "Экскаваторщик" },
    { civilian: "Водитель", spy: "Машинист" },

    // ========== ТРАНСПОРТ ==========
    { civilian: "Машина", spy: "Мотоцикл" },
    { civilian: "Самолёт", spy: "Вертолёт" },
    { civilian: "Автобус", spy: "Троллейбус" },
    { civilian: "Трамвай", spy: "Поезд" },
    { civilian: "Метро", spy: "Электричка" },
    { civilian: "Велосипед", spy: "Самокат" },
    { civilian: "Мопед", spy: "Скутер" },
    { civilian: "Грузовик", spy: "Самосвал" },
    { civilian: "Фура", spy: "Грузовик" },
    { civilian: "Трактор", spy: "Бульдозер" },
    { civilian: "Экскаватор", spy: "Погрузчик" },
    { civilian: "Кран", spy: "Вышка" },
    { civilian: "Танк", spy: "Бронетранспортёр" },
    { civilian: "Подводная лодка", spy: "Батискаф" },
    { civilian: "Катер", spy: "Яхта" },
    { civilian: "Лодка", spy: "Каяк" },
    { civilian: "Паром", spy: "Корабль" },
    { civilian: "Теплоход", spy: "Круизный лайнер" },
    { civilian: "Баржа", spy: "Сухогруз" },
    { civilian: "Танкер", spy: "Сухогруз" },
    { civilian: "Ледокол", spy: "Корабль" },
    { civilian: "Снегоход", spy: "Квадроцикл" },
    { civilian: "Джип", spy: "Внедорожник" },
    { civilian: "Седан", spy: "Хэтчбек" },
    { civilian: "Кроссовер", spy: "Универсал" },
    { civilian: "Кабриолет", spy: "Родстер" },
    { civilian: "Лимузин", spy: "Седан" },
    { civilian: "Минивэн", spy: "Микроавтобус" },
    { civilian: "Пикап", spy: "Грузовик" },
    { civilian: "Пожарная машина", spy: "Скорая помощь" },
    { civilian: "Полицейская машина", spy: "Скорая помощь" },
    { civilian: "Эвакуатор", spy: "Грузовик" },
    { civilian: "Такси", spy: "Каршеринг" },
    { civilian: "Гоночный болид", spy: "Карт" },
    { civilian: "Квадроцикл", spy: "Багги" },
    { civilian: "Гидроцикл", spy: "Катер" },
    { civilian: "Воздушный шар", spy: "Дирижабль" },

    // ========== ОДЕЖДА ==========
    { civilian: "Рубашка", spy: "Футболка" },
    { civilian: "Брюки", spy: "Джинсы" },
    { civilian: "Шорты", spy: "Бриджи" },
    { civilian: "Юбка", spy: "Платье" },
    { civilian: "Кофта", spy: "Свитер" },
    { civilian: "Куртка", spy: "Пальто" },
    { civilian: "Шуба", spy: "Дублёнка" },
    { civilian: "Плащ", spy: "Ветровка" },
    { civilian: "Толстовка", spy: "Худи" },
    { civilian: "Майка", spy: "Топ" },
    { civilian: "Носки", spy: "Гольфы" },
    { civilian: "Колготки", spy: "Чулки" },
    { civilian: "Леггинсы", spy: "Колготки" },
    { civilian: "Шапка", spy: "Кепка" },
    { civilian: "Бейсболка", spy: "Кепка" },
    { civilian: "Панама", spy: "Шляпа" },
    { civilian: "Шляпа", spy: "Кепка" },
    { civilian: "Берет", spy: "Шапка" },
    { civilian: "Перчатки", spy: "Варежки" },
    { civilian: "Шарф", spy: "Палантин" },
    { civilian: "Платок", spy: "Шарф" },
    { civilian: "Галстук", spy: "Бабочка" },
    { civilian: "Ремень", spy: "Пояс" },
    { civilian: "Кроссовки", spy: "Кеды" },
    { civilian: "Ботинки", spy: "Туфли" },
    { civilian: "Туфли", spy: "Лоферы" },
    { civilian: "Мокасины", spy: "Лоферы" },
    { civilian: "Сандалии", spy: "Босоножки" },
    { civilian: "Шлёпанцы", spy: "Вьетнамки" },
    { civilian: "Сапоги", spy: "Ботинки" },
    { civilian: "Угги", spy: "Сапоги" },
    { civilian: "Валенки", spy: "Угги" },
    { civilian: "Кимоно", spy: "Халат" },
    { civilian: "Халат", spy: "Пижама" },
    { civilian: "Пижама", spy: "Ночная рубашка" },
    { civilian: "Костюм", spy: "Смокинг" },
    { civilian: "Пиджак", spy: "Жакет" },
    { civilian: "Жилет", spy: "Безрукавка" },
    { civilian: "Комбинезон", spy: "Полукомбинезон" },
    { civilian: "Дождевик", spy: "Плащ" },
    { civilian: "Парка", spy: "Куртка" },
    { civilian: "Пуховик", spy: "Парка" },
    { civilian: "Тельняшка", spy: "Майка" },

    // ========== ДОМ И БЫТ ==========
    { civilian: "Диван", spy: "Кресло" },
    { civilian: "Кровать", spy: "Диван" },
    { civilian: "Стол", spy: "Парта" },
    { civilian: "Стул", spy: "Табурет" },
    { civilian: "Шкаф", spy: "Комод" },
    { civilian: "Тумба", spy: "Комод" },
    { civilian: "Полка", spy: "Стеллаж" },
    { civilian: "Зеркало", spy: "Окно" },
    { civilian: "Лампа", spy: "Светильник" },
    { civilian: "Люстра", spy: "Бра" },
    { civilian: "Торшер", spy: "Настольная лампа" },
    { civilian: "Ковёр", spy: "Палас" },
    { civilian: "Шторы", spy: "Занавески" },
    { civilian: "Подушка", spy: "Одеяло" },
    { civilian: "Плед", spy: "Одеяло" },
    { civilian: "Простыня", spy: "Пододеяльник" },
    { civilian: "Наволочка", spy: "Простыня" },
    { civilian: "Матрас", spy: "Кровать" },
    { civilian: "Раковина", spy: "Умывальник" },
    { civilian: "Ванна", spy: "Душ" },
    { civilian: "Унитаз", spy: "Биде" },
    { civilian: "Кран", spy: "Смеситель" },
    { civilian: "Плита", spy: "Духовка" },
    { civilian: "Микроволновка", spy: "Духовка" },
    { civilian: "Холодильник", spy: "Морозилка" },
    { civilian: "Стиральная машина", spy: "Посудомоечная машина" },
    { civilian: "Пылесос", spy: "Швабра" },
    { civilian: "Веник", spy: "Щётка" },
    { civilian: "Кастрюля", spy: "Сковорода" },
    { civilian: "Чайник", spy: "Кофеварка" },
    { civilian: "Тостер", spy: "Микроволновка" },
    { civilian: "Блендер", spy: "Миксер" },
    { civilian: "Мясорубка", spy: "Блендер" },
    { civilian: "Тарелка", spy: "Миска" },
    { civilian: "Чашка", spy: "Кружка" },
    { civilian: "Стакан", spy: "Бокал" },
    { civilian: "Вилка", spy: "Ложка" },
    { civilian: "Ложка", spy: "Чайная ложка" },
    { civilian: "Нож", spy: "Скалка" },
    { civilian: "Доска", spy: "Скалка" },
    { civilian: "Тёрка", spy: "Овощечистка" },
    { civilian: "Дуршлаг", spy: "Сито" },
    { civilian: "Половник", spy: "Ложка" },
    { civilian: "Открывалка", spy: "Штопор" },
    { civilian: "Полотенце", spy: "Салфетка" },
    { civilian: "Скатерть", spy: "Салфетка" },
    { civilian: "Мыло", spy: "Гель для душа" },

    // ========== ГЕОГРАФИЯ ==========
    { civilian: "Москва", spy: "Санкт-Петербург" },
    { civilian: "Франция", spy: "Италия" },
    { civilian: "Испания", spy: "Португалия" },
    { civilian: "Германия", spy: "Австрия" },
    { civilian: "Швейцария", spy: "Австрия" },
    { civilian: "Швеция", spy: "Норвегия" },
    { civilian: "Дания", spy: "Швеция" },
    { civilian: "Финляндия", spy: "Норвегия" },
    { civilian: "Польша", spy: "Чехия" },
    { civilian: "Венгрия", spy: "Румыния" },
    { civilian: "Болгария", spy: "Сербия" },
    { civilian: "Греция", spy: "Италия" },
    { civilian: "Турция", spy: "Греция" },
    { civilian: "Египет", spy: "Марокко" },
    { civilian: "Китай", spy: "Япония" },
    { civilian: "Корея", spy: "Япония" },
    { civilian: "Таиланд", spy: "Вьетнам" },
    { civilian: "Индия", spy: "Пакистан" },
    { civilian: "Бразилия", spy: "Аргентина" },
    { civilian: "Мексика", spy: "Бразилия" },
    { civilian: "Канада", spy: "США" },
    { civilian: "Австралия", spy: "Новая Зеландия" },
    { civilian: "Антарктида", spy: "Арктика" },
    { civilian: "Атлантический океан", spy: "Тихий океан" },
    { civilian: "Средиземное море", spy: "Чёрное море" },
    { civilian: "Эверест", spy: "Эльбрус" },
    { civilian: "Байкал", spy: "Ладожское озеро" },
    { civilian: "Волга", spy: "Дон" },
    { civilian: "Нил", spy: "Амазонка" },
    { civilian: "Сахара", spy: "Гоби" },
    { civilian: "Альпы", spy: "Кавказ" },
    { civilian: "Сибирь", spy: "Дальний Восток" },
    { civilian: "Крым", spy: "Кавказ" },
    { civilian: "Урал", spy: "Кавказ" },
    { civilian: "Тундра", spy: "Степь" },

    // ========== СПОРТ И ФИТНЕС ==========
    { civilian: "Футбол", spy: "Регби" },
    { civilian: "Баскетбол", spy: "Волейбол" },
    { civilian: "Теннис", spy: "Бадминтон" },
    { civilian: "Хоккей", spy: "Кёрлинг" },
    { civilian: "Бокс", spy: "Борьба" },
    { civilian: "Дзюдо", spy: "Самбо" },
    { civilian: "Каратэ", spy: "Тхэквондо" },
    { civilian: "Плавание", spy: "Дайвинг" },
    { civilian: "Бег", spy: "Спортивная ходьба" },
    { civilian: "Велоспорт", spy: "Мотоспорт" },
    { civilian: "Гимнастика", spy: "Акробатика" },
    { civilian: "Фехтование", spy: "Стрельба" },
    { civilian: "Гольф", spy: "Крикет" },
    { civilian: "Бейсбол", spy: "Софтбол" },
    { civilian: "Скейтбординг", spy: "Сёрфинг" },
    { civilian: "Лыжи", spy: "Сноуборд" },
    { civilian: "Фигурное катание", spy: "Хоккей" },
    { civilian: "Тяжёлая атлетика", spy: "Пауэрлифтинг" },
    { civilian: "Йога", spy: "Пилатес" },
    { civilian: "Аэробика", spy: "Фитнес" },
    { civilian: "Кроссфит", spy: "Бодибилдинг" },
    { civilian: "Альпинизм", spy: "Скалолазание" },
    { civilian: "Парашютный спорт", spy: "Дельтапланеризм" },
    { civilian: "Бобслей", spy: "Санный спорт" },
    { civilian: "Биатлон", spy: "Лыжные гонки" },
    { civilian: "Скачки", spy: "Конкур" },
    { civilian: "Гандбол", spy: "Волейбол" },
    { civilian: "Водное поло", spy: "Гандбол" },
    { civilian: "Синхронное плавание", spy: "Плавание" },
    { civilian: "Прыжки в воду", spy: "Дайвинг" },
    { civilian: "Шахматы", spy: "Шашки" },
    { civilian: "Киберспорт", spy: "Шахматы" },
    { civilian: "Настольный теннис", spy: "Бадминтон" },
    { civilian: "Сёрфинг", spy: "Виндсёрфинг" },
    { civilian: "Каякинг", spy: "Рафтинг" },
    { civilian: "Триатлон", spy: "Пятиборье" },
    { civilian: "Марафон", spy: "Полумарафон" },
    { civilian: "Спринт", spy: "Бег" },
    { civilian: "Ориентирование", spy: "Туризм" },
    { civilian: "Пейнтбол", spy: "Страйкбол" },
    { civilian: "Паркур", spy: "Скейтбординг" },
    { civilian: "Спортивные танцы", spy: "Бальные танцы" },
    { civilian: "Чирлидинг", spy: "Гимнастика" },

    // ========== ШКОЛА И НАУКА ==========
    { civilian: "Математика", spy: "Алгебра" },
    { civilian: "Геометрия", spy: "Тригонометрия" },
    { civilian: "Физика", spy: "Астрономия" },
    { civilian: "Химия", spy: "Биология" },
    { civilian: "История", spy: "Обществознание" },
    { civilian: "Литература", spy: "Русский язык" },
    { civilian: "География", spy: "Экология" },
    { civilian: "Информатика", spy: "Программирование" },
    { civilian: "Физкультура", spy: "Спорт" },
    { civilian: "Музыка", spy: "ИЗО" },
    { civilian: "Технология", spy: "Труд" },
    { civilian: "Английский язык", spy: "Немецкий язык" },
    { civilian: "Французский язык", spy: "Испанский язык" },
    { civilian: "Философия", spy: "Логика" },
    { civilian: "Психология", spy: "Социология" },
    { civilian: "Экономика", spy: "Менеджмент" },
    { civilian: "Маркетинг", spy: "Реклама" },
    { civilian: "Юриспруденция", spy: "Политология" },
    { civilian: "Медицина", spy: "Фармакология" },
    { civilian: "Анатомия", spy: "Физиология" },
    { civilian: "Археология", spy: "Палеонтология" },
    { civilian: "Метеорология", spy: "Климатология" },
    { civilian: "Теорема", spy: "Аксиома" },
    { civilian: "Формула", spy: "Уравнение" },
    { civilian: "Гипотеза", spy: "Теория" },
    { civilian: "Эксперимент", spy: "Наблюдение" },
    { civilian: "Исследование", spy: "Анализ" },
    { civilian: "Статистика", spy: "Вероятность" },
    { civilian: "Алгоритм", spy: "Программа" },
    { civilian: "База данных", spy: "Таблица" },
    { civilian: "Процессор", spy: "Микросхема" },
    { civilian: "Робот", spy: "Автомат" },
    { civilian: "Искусственный интеллект", spy: "Нейросеть" },
    { civilian: "Виртуальная реальность", spy: "Дополненная реальность" },
    { civilian: "Микроскоп", spy: "Телескоп" },
    { civilian: "Лаборатория", spy: "Клиника" },
    { civilian: "Библиотека", spy: "Архив" },
    { civilian: "Семинар", spy: "Лекция" },
    { civilian: "Экзамен", spy: "Зачёт" },
    { civilian: "Диплом", spy: "Аттестат" },

    // ========== ИСКУССТВО И КУЛЬТУРА ==========
    { civilian: "Живопись", spy: "Графика" },
    { civilian: "Скульптура", spy: "Архитектура" },
    { civilian: "Поэзия", spy: "Проза" },
    { civilian: "Театр", spy: "Опера" },
    { civilian: "Балет", spy: "Танцы" },
    { civilian: "Кино", spy: "Телевидение" },
    { civilian: "Фотография", spy: "Живопись" },
    { civilian: "Музыка", spy: "Пение" },
    { civilian: "Джаз", spy: "Блюз" },
    { civilian: "Рок", spy: "Металл" },
    { civilian: "Поп-музыка", spy: "Рэп" },
    { civilian: "Классическая музыка", spy: "Джаз" },
    { civilian: "Комикс", spy: "Манга" },
    { civilian: "Мультфильм", spy: "Аниме" },
    { civilian: "Роман", spy: "Новелла" },
    { civilian: "Рассказ", spy: "Повесть" },
    { civilian: "Сказка", spy: "Былина" },
    { civilian: "Миф", spy: "Легенда" },
    { civilian: "Сонет", spy: "Баллада" },
    { civilian: "Романс", spy: "Песня" },
    { civilian: "Симфония", spy: "Соната" },
    { civilian: "Опера", spy: "Оперетта" },
    { civilian: "Мюзикл", spy: "Опера" },
    { civilian: "Трагедия", spy: "Комедия" },
    { civilian: "Драма", spy: "Мелодрама" },
    { civilian: "Пантомима", spy: "Скетч" },
    { civilian: "Карикатура", spy: "Шарж" },
    { civilian: "Натюрморт", spy: "Пейзаж" },
    { civilian: "Портрет", spy: "Автопортрет" },
    { civilian: "Мозаика", spy: "Витраж" },
    { civilian: "Фреска", spy: "Граффити" },
    { civilian: "Керамика", spy: "Фарфор" },
    { civilian: "Каллиграфия", spy: "Типографика" },
    { civilian: "Орнамент", spy: "Узор" },
    { civilian: "Хореография", spy: "Импровизация" },
    { civilian: "Режиссура", spy: "Сценарий" },
    { civilian: "Монтаж", spy: "Съёмка" },
    { civilian: "Дубляж", spy: "Озвучка" },
    { civilian: "Сценарий", spy: "Пьеса" },
    { civilian: "Партитура", spy: "Ноты" },
    { civilian: "Дирижёр", spy: "Композитор" },
    { civilian: "Художник", spy: "Скульптор" },

    // ========== ПРИРОДА И ПОГОДА ==========
    { civilian: "Дождь", spy: "Ливень" },
    { civilian: "Снег", spy: "Град" },
    { civilian: "Ветер", spy: "Ураган" },
    { civilian: "Торнадо", spy: "Смерч" },
    { civilian: "Тайфун", spy: "Ураган" },
    { civilian: "Гроза", spy: "Молния" },
    { civilian: "Гром", spy: "Молния" },
    { civilian: "Туман", spy: "Дымка" },
    { civilian: "Радуга", spy: "Северное сияние" },
    { civilian: "Роса", spy: "Иней" },
    { civilian: "Изморозь", spy: "Иней" },
    { civilian: "Засуха", spy: "Наводнение" },
    { civilian: "Цунами", spy: "Прилив" },
    { civilian: "Отлив", spy: "Прилив" },
    { civilian: "Шторм", spy: "Буря" },
    { civilian: "Метель", spy: "Пурга" },
    { civilian: "Вьюга", spy: "Метель" },
    { civilian: "Жара", spy: "Зной" },
    { civilian: "Холод", spy: "Мороз" },
    { civilian: "Оттепель", spy: "Потепление" },
    { civilian: "Похолодание", spy: "Мороз" },
    { civilian: "Весна", spy: "Осень" },
    { civilian: "Лето", spy: "Зима" },
    { civilian: "Восход", spy: "Закат" },
    { civilian: "Затмение", spy: "Полнолуние" },
    { civilian: "Звезда", spy: "Планета" },
    { civilian: "Комета", spy: "Метеорит" },
    { civilian: "Астероид", spy: "Метеорит" },
    { civilian: "Галактика", spy: "Вселенная" },
    { civilian: "Гора", spy: "Холм" },
    { civilian: "Равнина", spy: "Плоскость" },
    { civilian: "Овраг", spy: "Ущелье" },
    { civilian: "Каньон", spy: "Ущелье" },
    { civilian: "Пещера", spy: "Грот" },
    { civilian: "Вулкан", spy: "Гейзер" },
    { civilian: "Остров", spy: "Полуостров" },
    { civilian: "Материк", spy: "Континент" },
    { civilian: "Архипелаг", spy: "Остров" },
    { civilian: "Пустыня", spy: "Степь" },
    { civilian: "Лес", spy: "Роща" },
    { civilian: "Тайга", spy: "Лес" },
    { civilian: "Джунгли", spy: "Лес" },
    { civilian: "Болото", spy: "Трясина" },
    { civilian: "Озеро", spy: "Пруд" },
    { civilian: "Река", spy: "Ручей" },
    { civilian: "Водопад", spy: "Порог" },

    // ========== ТЕХНОЛОГИИ И ГАДЖЕТЫ ==========
    { civilian: "Смартфон", spy: "Планшет" },
    { civilian: "Ноутбук", spy: "Компьютер" },
    { civilian: "Телевизор", spy: "Монитор" },
    { civilian: "Принтер", spy: "Сканер" },
    { civilian: "Клавиатура", spy: "Мышь" },
    { civilian: "Наушники", spy: "Колонки" },
    { civilian: "Микрофон", spy: "Наушники" },
    { civilian: "Флешка", spy: "Карта памяти" },
    { civilian: "Жёсткий диск", spy: "SSD" },
    { civilian: "Процессор", spy: "Видеокарта" },
    { civilian: "Материнская плата", spy: "Процессор" },
    { civilian: "Роутер", spy: "Модем" },
    { civilian: "Сервер", spy: "Компьютер" },
    { civilian: "Облако", spy: "Хранилище" },
    { civilian: "Интернет", spy: "Сеть" },
    { civilian: "Wi-Fi", spy: "Bluetooth" },
    { civilian: "USB", spy: "HDMI" },
    { civilian: "Батарея", spy: "Аккумулятор" },
    { civilian: "Зарядка", spy: "Батарея" },
    { civilian: "Дрон", spy: "Вертолёт" },
    { civilian: "Квадрокоптер", spy: "Дрон" },
    { civilian: "Робот-пылесос", spy: "Робот" },
    { civilian: "Умные часы", spy: "Фитнес-браслет" },
    { civilian: "VR-шлем", spy: "Очки" },
    { civilian: "3D-принтер", spy: "Принтер" },
    { civilian: "Камера", spy: "Видеокамера" },
    { civilian: "Фотоаппарат", spy: "Камера" },
    { civilian: "Проектор", spy: "Монитор" },
    { civilian: "Гарнитура", spy: "Наушники" },
    { civilian: "Сабвуфер", spy: "Колонка" },
    { civilian: "Плеер", spy: "Магнитофон" },
    { civilian: "Радио", spy: "Телевизор" },
    { civilian: "Кондиционер", spy: "Вентилятор" },
    { civilian: "Обогреватель", spy: "Кондиционер" },
    { civilian: "Холодильник", spy: "Морозильник" },
    { civilian: "Электроплита", spy: "Газовая плита" },
    { civilian: "Микроволновка", spy: "Духовой шкаф" },
    { civilian: "Чайник электрический", spy: "Чайник" },
    { civilian: "Кофемашина", spy: "Кофеварка" },
    { civilian: "Посудомоечная машина", spy: "Стиральная машина" },
    { civilian: "Пылесос", spy: "Робот-пылесос" },
    { civilian: "Утюг", spy: "Парогенератор" },
    { civilian: "Фен", spy: "Плойка" },
    { civilian: "Бритва электрическая", spy: "Триммер" },
    { civilian: "Секундомер", spy: "Таймер" },
    { civilian: "Калькулятор", spy: "Компьютер" },
    { civilian: "Видеорегистратор", spy: "Камера" },

    // ========== КОСМОС ==========
    { civilian: "Планета", spy: "Звезда" },
    { civilian: "Солнце", spy: "Луна" },
    { civilian: "Марс", spy: "Венера" },
    { civilian: "Юпитер", spy: "Сатурн" },
    { civilian: "Уран", spy: "Нептун" },
    { civilian: "Меркурий", spy: "Марс" },
    { civilian: "Земля", spy: "Марс" },
    { civilian: "Галактика", spy: "Вселенная" },
    { civilian: "Комета", spy: "Астероид" },
    { civilian: "Метеор", spy: "Метеорит" },
    { civilian: "Чёрная дыра", spy: "Нейтронная звезда" },
    { civilian: "Ракета", spy: "Шаттл" },
    { civilian: "Космонавт", spy: "Астронавт" },
    { civilian: "Спутник", spy: "Луна" },
    { civilian: "Орбита", spy: "Траектория" },
    { civilian: "Созвездие", spy: "Звезда" },
    { civilian: "Большая Медведица", spy: "Малая Медведица" },
    { civilian: "Телескоп", spy: "Обсерватория" },
    { civilian: "Космодром", spy: "Аэропорт" },
    { civilian: "Невесомость", spy: "Гравитация" },
    { civilian: "Атмосфера", spy: "Стратосфера" },
    { civilian: "Кислород", spy: "Углекислый газ" },
    { civilian: "Скафандр", spy: "Костюм" },
    { civilian: "Станция", spy: "Корабль" },
    { civilian: "Гравитация", spy: "Магнетизм" },
    { civilian: "Световой год", spy: "Километр" },

    // ========== МУЗЫКАЛЬНЫЕ ИНСТРУМЕНТЫ ==========
    { civilian: "Гитара", spy: "Укулеле" },
    { civilian: "Скрипка", spy: "Альт" },
    { civilian: "Виолончель", spy: "Контрабас" },
    { civilian: "Пианино", spy: "Рояль" },
    { civilian: "Синтезатор", spy: "Орган" },
    { civilian: "Аккордеон", spy: "Баян" },
    { civilian: "Гармонь", spy: "Аккордеон" },
    { civilian: "Флейта", spy: "Кларнет" },
    { civilian: "Саксофон", spy: "Труба" },
    { civilian: "Труба", spy: "Тромбон" },
    { civilian: "Барабан", spy: "Бубен" },
    { civilian: "Тарелки", spy: "Барабан" },
    { civilian: "Ксилофон", spy: "Маримба" },
    { civilian: "Арфа", spy: "Лира" },
    { civilian: "Балалайка", spy: "Домра" },
    { civilian: "Контрабас", spy: "Виолончель" },
    { civilian: "Электрогитара", spy: "Гитара" },
    { civilian: "Бас-гитара", spy: "Гитара" },
    { civilian: "Фортепиано", spy: "Пианино" },
    { civilian: "Мандолина", spy: "Лютня" },
    { civilian: "Банджо", spy: "Гитара" },
    { civilian: "Кастаньеты", spy: "Маракасы" },
    { civilian: "Тамбурин", spy: "Бубен" },

    // ========== МЕДИЦИНА И ЗДОРОВЬЕ ==========
    { civilian: "Врач", spy: "Медсестра" },
    { civilian: "Хирург", spy: "Анестезиолог" },
    { civilian: "Терапевт", spy: "Педиатр" },
    { civilian: "Кардиолог", spy: "Невролог" },
    { civilian: "Онколог", spy: "Хирург" },
    { civilian: "Гинеколог", spy: "Уролог" },
    { civilian: "Офтальмолог", spy: "Окулист" },
    { civilian: "Стоматолог", spy: "Ортодонт" },
    { civilian: "Психолог", spy: "Психиатр" },
    { civilian: "Логопед", spy: "Дефектолог" },
    { civilian: "Массаж", spy: "Физиотерапия" },
    { civilian: "Вакцинация", spy: "Прививка" },
    { civilian: "Анализ крови", spy: "Анализ мочи" },
    { civilian: "УЗИ", spy: "МРТ" },
    { civilian: "Рентген", spy: "Флюорография" },
    { civilian: "ЭКГ", spy: "УЗИ" },
    { civilian: "Томография", spy: "Рентген" },
    { civilian: "Диагноз", spy: "Симптом" },
    { civilian: "Лечение", spy: "Профилактика" },
    { civilian: "Реабилитация", spy: "Лечение" },
    { civilian: "Рецепт", spy: "Назначение" },
    { civilian: "Больница", spy: "Поликлиника" },
    { civilian: "Аптека", spy: "Оптика" },
    { civilian: "Скорая помощь", spy: "Неотложка" },
    { civilian: "Инфекция", spy: "Бактерия" },
    { civilian: "Вирус", spy: "Бактерия" },
    { civilian: "Микроб", spy: "Бактерия" },
    { civilian: "Антибиотик", spy: "Противовирусное" },
    { civilian: "Витамин", spy: "Минерал" },
    { civilian: "Диета", spy: "Питание" },
    { civilian: "Калории", spy: "Энергия" },
    { civilian: "Бессонница", spy: "Усталость" },
    { civilian: "Стресс", spy: "Депрессия" },
    { civilian: "Аллергия", spy: "Простуда" },
    { civilian: "Грипп", spy: "ОРВИ" },
    { civilian: "Ангина", spy: "Бронхит" },
    { civilian: "Пневмония", spy: "Бронхит" },
    { civilian: "Астма", spy: "Бронхит" },

    // ========== ЦВЕТА И ОТТЕНКИ ==========
    { civilian: "Красный", spy: "Алый" },
    { civilian: "Алый", spy: "Бордовый" },
    { civilian: "Бордовый", spy: "Вишнёвый" },
    { civilian: "Вишнёвый", spy: "Малиновый" },
    { civilian: "Розовый", spy: "Красный" },
    { civilian: "Оранжевый", spy: "Жёлтый" },
    { civilian: "Жёлтый", spy: "Лимонный" },
    { civilian: "Лимонный", spy: "Золотой" },
    { civilian: "Золотой", spy: "Жёлтый" },
    { civilian: "Зелёный", spy: "Изумрудный" },
    { civilian: "Изумрудный", spy: "Салатовый" },
    { civilian: "Салатовый", spy: "Зелёный" },
    { civilian: "Голубой", spy: "Синий" },
    { civilian: "Синий", spy: "Индиго" },
    { civilian: "Индиго", spy: "Фиолетовый" },
    { civilian: "Фиолетовый", spy: "Пурпурный" },
    { civilian: "Пурпурный", spy: "Сиреневый" },
    { civilian: "Сиреневый", spy: "Фиолетовый" },
    { civilian: "Белый", spy: "Чёрный" },
    { civilian: "Серый", spy: "Чёрный" },
    { civilian: "Бежевый", spy: "Кремовый" },
    { civilian: "Кремовый", spy: "Белый" },
    { civilian: "Коричневый", spy: "Шоколадный" },
    { civilian: "Шоколадный", spy: "Бежевый" },
    { civilian: "Бирюзовый", spy: "Голубой" },
    { civilian: "Лазурный", spy: "Голубой" },
    { civilian: "Хаки", spy: "Оливковый" },
    { civilian: "Оливковый", spy: "Зелёный" },
    { civilian: "Циан", spy: "Бирюзовый" },
    { civilian: "Коралловый", spy: "Оранжевый" },
    { civilian: "Лососевый", spy: "Розовый" },
    { civilian: "Персиковый", spy: "Оранжевый" },
    { civilian: "Мятный", spy: "Зелёный" },
    { civilian: "Морская волна", spy: "Бирюзовый" },
    { civilian: "Ультрамарин", spy: "Синий" },
    { civilian: "Фуксия", spy: "Розовый" },

    // ========== ЭМОЦИИ И ЧУВСТВА ==========
    { civilian: "Радость", spy: "Счастье" },
    { civilian: "Счастье", spy: "Восторг" },
    { civilian: "Восторг", spy: "Эйфория" },
    { civilian: "Грусть", spy: "Печаль" },
    { civilian: "Печаль", spy: "Тоска" },
    { civilian: "Тоска", spy: "Меланхолия" },
    { civilian: "Гнев", spy: "Ярость" },
    { civilian: "Страх", spy: "Боязнь" },
    { civilian: "Ужас", spy: "Паника" },
    { civilian: "Тревога", spy: "Беспокойство" },
    { civilian: "Беспокойство", spy: "Волнение" },
    { civilian: "Удивление", spy: "Изумление" },
    { civilian: "Изумление", spy: "Шок" },
    { civilian: "Отвращение", spy: "Неприязнь" },
    { civilian: "Любовь", spy: "Симпатия" },
    { civilian: "Симпатия", spy: "Привязанность" },
    { civilian: "Ненависть", spy: "Злость" },
    { civilian: "Зависть", spy: "Ревность" },
    { civilian: "Обида", spy: "Разочарование" },
    { civilian: "Разочарование", spy: "Досада" },
    { civilian: "Вина", spy: "Стыд" },
    { civilian: "Стыд", spy: "Смущение" },
    { civilian: "Гордость", spy: "Тщеславие" },
    { civilian: "Скромность", spy: "Застенчивость" },
    { civilian: "Интерес", spy: "Любопытство" },
    { civilian: "Скука", spy: "Апатия" },
    { civilian: "Надежда", spy: "Вера" },
    { civilian: "Вера", spy: "Доверие" },
    { civilian: "Нежность", spy: "Ласка" },
    { civilian: "Уважение", spy: "Почитание" },
    { civilian: "Восхищение", spy: "Обожание" },
    { civilian: "Сострадание", spy: "Жалость" },
    { civilian: "Благодарность", spy: "Признательность" },
    { civilian: "Удовлетворение", spy: "Довольство" },
    { civilian: "Спокойствие", spy: "Умиротворение" },

    // ========== ХОББИ И РАЗВЛЕЧЕНИЯ ==========
    { civilian: "Рыбалка", spy: "Охота" },
    { civilian: "Садоводство", spy: "Огородничество" },
    { civilian: "Кулинария", spy: "Выпечка" },
    { civilian: "Вязание", spy: "Шитьё" },
    { civilian: "Шитьё", spy: "Вышивание" },
    { civilian: "Вышивание", spy: "Вязание" },
    { civilian: "Рисование", spy: "Живопись" },
    { civilian: "Фотография", spy: "Видеосъёмка" },
    { civilian: "Коллекционирование", spy: "Антиквариат" },
    { civilian: "Моделирование", spy: "Конструирование" },
    { civilian: "Шахматы", spy: "Шашки" },
    { civilian: "Настольные игры", spy: "Карты" },
    { civilian: "Пазлы", spy: "Настольные игры" },
    { civilian: "Чтение", spy: "Письмо" },
    { civilian: "Писательство", spy: "Поэзия" },
    { civilian: "Музыка", spy: "Пение" },
    { civilian: "Игра на гитаре", spy: "Игра на пианино" },
    { civilian: "Танцы", spy: "Хореография" },
    { civilian: "Йога", spy: "Медитация" },
    { civilian: "Медитация", spy: "Релаксация" },
    { civilian: "Путешествия", spy: "Туризм" },
    { civilian: "Туризм", spy: "Походы" },
    { civilian: "Альпинизм", spy: "Скалолазание" },
    { civilian: "Дайвинг", spy: "Снорклинг" },
    { civilian: "Сёрфинг", spy: "Виндсёрфинг" },
    { civilian: "Скейтбординг", spy: "Ролики" },
    { civilian: "Велосипед", spy: "Мотоцикл" },
    { civilian: "Автомобили", spy: "Мотоциклы" },
    { civilian: "Астрономия", spy: "Телескоп" },
    { civilian: "Волонтёрство", spy: "Благотворительность" },
    { civilian: "Рукоделие", spy: "Творчество" },
    { civilian: "Мыловарение", spy: "Свечеварение" },
    { civilian: "Декорирование", spy: "Дизайн интерьера" },
    { civilian: "Кино", spy: "Театр" },
];

// Проверка на уникальность и количество
console.log(`Всего пар: ${WORD_PAIRS.length}`);