const FACTS = [
    // ========== ЖИВОТНЫЕ (80 фактов) ==========
    { fact: "Пингвины живут только в Антарктиде", isTrue: false },
    { fact: "Медведи на самом деле не впадают в спячку, а чутко дремлют", isTrue: true },
    { fact: "Верблюды хранят воду в горбах", isTrue: false },
    { fact: "Улитка может спать три года подряд", isTrue: true },
    { fact: "Страусы прячут голову в песок при опасности", isTrue: false },
    { fact: "Медоносная пчела может ужалить только один раз", isTrue: true },
    { fact: "Некоторым акулам нужно постоянно плавать, чтобы дышать", isTrue: true },
    { fact: "Кошки видят в полной темноте", isTrue: false },
    { fact: "Дельфины спят с одним открытым глазом", isTrue: true },
    { fact: "Глаз страуса больше, чем его мозг", isTrue: true },
    { fact: "Сердце синего кита размером с автомобиль", isTrue: true },
    { fact: "У пауков шесть ног", isTrue: false },
    { fact: "Осьминог имеет три сердца", isTrue: true },
    { fact: "Волк воет на луну от голода", isTrue: false },
    { fact: "Муравьи спят около 4-5 часов в день", isTrue: true },
    { fact: "Бабочки пробуют пищу лапками", isTrue: true },
    { fact: "У золотой рыбки память 3 секунды", isTrue: false },
    { fact: "Кролики едят морковь в дикой природе", isTrue: false },
    { fact: "Летучие мыши слепые", isTrue: false },
    { fact: "Совы могут поворачивать голову на 360 градусов", isTrue: false },
    { fact: "Хамелеон меняет цвет для маскировки", isTrue: false },
    { fact: "Пчелы умеют считать до четырёх", isTrue: true },
    { fact: "Собаки охлаждаются, высовывая язык", isTrue: true },
    { fact: "Жирафы спят всего 1-2 часа в день", isTrue: true },
    { fact: "Кошки мурлыкают только когда довольны", isTrue: false },
    { fact: "Пингвины умеют летать", isTrue: false },
    { fact: "У тигра полосатая кожа, а не только шерсть", isTrue: true },
    { fact: "Кенгуру не умеют прыгать назад", isTrue: true },
    { fact: "Ленивцы спят до 20 часов в день", isTrue: true },
    { fact: "У белых медведей чёрная кожа", isTrue: true },
    { fact: "Слоны умеют плавать", isTrue: true },
    { fact: "У кошки 9 жизней", isTrue: false },
    { fact: "Крокодилы плачут, когда едят", isTrue: false },
    { fact: "У осьминога голубая кровь", isTrue: true },
    { fact: "Лошади спят стоя", isTrue: true },
    { fact: "Летучие мыши — это птицы", isTrue: false },
    { fact: "Улитки имеют зубы", isTrue: true },
    { fact: "Черепахи могут выходить из панциря", isTrue: false },
    { fact: "Пингвины умеют плавать", isTrue: true },
    { fact: "У жирафа столько же шейных позвонков, сколько у человека", isTrue: true },
    { fact: "Собаки различают цвета", isTrue: true },
    { fact: "Кошки не чувствуют сладкий вкус", isTrue: true },
    { fact: "Хомяки запасают еду в щеках", isTrue: true },
    { fact: "Слоны боятся мышей", isTrue: false },
    { fact: "Волки — предки собак", isTrue: true },
    { fact: "Змеи имеют веки", isTrue: false },
    { fact: "Пингвины дарят друг другу камни", isTrue: true },
    { fact: "У коровы четыре желудка", isTrue: true },
    { fact: "Совы не умеют двигать глазами", isTrue: true },
    { fact: "Дельфины — это рыбы", isTrue: false },
    { fact: "У пчелы пять глаз", isTrue: true },
    { fact: "Муравьи могут поднять вес в 50 раз больше своего", isTrue: true },
    { fact: "Лягушки пьют воду ртом", isTrue: false },
    { fact: "У паука восемь глаз", isTrue: true },
    { fact: "Мыши боятся кошек", isTrue: true },
    { fact: "Крокодилы — родственники динозавров", isTrue: true },
    { fact: "У акулы нет костей", isTrue: true },
    { fact: "Гепард — самое быстрое животное", isTrue: true },
    { fact: "Слон — самое большое животное на суше", isTrue: true },
    { fact: "Синий кит — самое большое животное на планете", isTrue: true },
    { fact: "Слоны не умеют прыгать", isTrue: true },
    { fact: "Ленивцы — самые медленные животные", isTrue: true },
    { fact: "Пингвины откладывают яйца", isTrue: true },
    { fact: "Все акулы откладывают яйца", isTrue: false },
    { fact: "У жирафа длинный язык", isTrue: true },
    { fact: "Колибри умеют летать назад", isTrue: true },
    { fact: "У страуса есть крылья", isTrue: true },
    { fact: "Пингвины — это млекопитающие", isTrue: false },
    { fact: "У слона есть хобот", isTrue: true },
    { fact: "У осьминога восемь щупалец", isTrue: true },
    { fact: "У паука восемь ног", isTrue: true },
    { fact: "У муравья шесть ног", isTrue: true },
    { fact: "Пчёлы живут в ульях", isTrue: true },
    { fact: "Медведи едят мёд", isTrue: true },
    { fact: "Лисы — хищники", isTrue: true },
    { fact: "Зайцы — хищники", isTrue: false },
    { fact: "Белки едят орехи", isTrue: true },
    { fact: "Ёжики едят грибы", isTrue: true },
    { fact: "Волки живут стаями", isTrue: true },
    { fact: "Тигры живут стаями", isTrue: false },
    { fact: "Львы живут прайдами", isTrue: true },
    { fact: "Кенгуру носят детёнышей в сумке", isTrue: true },
    { fact: "Коалы едят бамбук", isTrue: false },
    { fact: "Панды едят бамбук", isTrue: true },
    { fact: "Верблюды живут в пустыне", isTrue: true },
    { fact: "Белые медведи живут в Антарктиде", isTrue: false },
    { fact: "Пингвины живут в Арктике", isTrue: false },
    { fact: "Крокодилы живут в реках", isTrue: true },
    { fact: "Акулы живут в океанах", isTrue: true },
    { fact: "Дельфины живут в океанах", isTrue: true },
    { fact: "Киты — это рыбы", isTrue: false },
    { fact: "Тюлени — это рыбы", isTrue: false },
    { fact: "Моржи имеют бивни", isTrue: true },
    { fact: "У белого медведя белая шерсть", isTrue: true },
    { fact: "У зебры полоски", isTrue: true },
    { fact: "У леопарда пятна", isTrue: true },
    { fact: "У слона большие уши", isTrue: true },
    { fact: "У зайца длинные уши", isTrue: true },
    { fact: "У лисы пушистый хвост", isTrue: true },
    { fact: "У белки пушистый хвост", isTrue: true },
    { fact: "У павлина красивый хвост", isTrue: true },
    { fact: "У петуха гребешок", isTrue: true },
    { fact: "У курицы гребешок", isTrue: false },
    { fact: "У индюка бородка", isTrue: true },
    { fact: "У гуся длинная шея", isTrue: true },
    { fact: "У лебедя длинная шея", isTrue: true },
    { fact: "У жирафа длинная шея", isTrue: true },
    { fact: "У черепахи есть панцирь", isTrue: true },
    { fact: "У улитки есть раковина", isTrue: true },
    { fact: "У рака есть клешни", isTrue: true },
    { fact: "У краба есть клешни", isTrue: true },
    { fact: "У пчелы есть жало", isTrue: true },
    { fact: "У комара есть хоботок", isTrue: true },
    { fact: "У бабочки есть крылья", isTrue: true },
    { fact: "У стрекозы есть крылья", isTrue: true },
    { fact: "У божьей коровки есть пятнышки", isTrue: true },
    { fact: "У светлячка есть светящийся орган", isTrue: true },
    { fact: "У сверчка есть усики", isTrue: true },
    { fact: "У таракана есть усы", isTrue: true },
    { fact: "У мухи есть крылья", isTrue: true },
    { fact: "У паука есть паутина", isTrue: true },
    { fact: "У червя нет ног", isTrue: true },
    { fact: "У змеи нет ног", isTrue: true },
    { fact: "У ящерицы есть хвост", isTrue: true },
    { fact: "У лягушки есть перепонки на лапах", isTrue: true },
    { fact: "У рыбы есть жабры", isTrue: true },
    { fact: "У птицы есть перья", isTrue: true },
    { fact: "У собаки есть хвост", isTrue: true },
    { fact: "У кошки есть усы", isTrue: true },
    { fact: "У кролика есть длинные уши", isTrue: true },
    { fact: "У хомяка есть защёчные мешки", isTrue: true },
    { fact: "У белки есть цепкие лапы", isTrue: true },
    { fact: "У ежа есть иголки", isTrue: true },
    { fact: "У дикобраза есть иголки", isTrue: true },
    { fact: "У скунса есть защитная жидкость с резким запахом", isTrue: true },
    { fact: "У кенгуру есть сумка", isTrue: true },
    { fact: "У коалы есть сумка", isTrue: true },
    { fact: "У опоссума есть сумка", isTrue: true },
    { fact: "У слона есть бивни", isTrue: true },
    { fact: "У моржа есть бивни", isTrue: true },
    { fact: "У кабана есть клыки", isTrue: true },
    { fact: "У тигра есть клыки", isTrue: true },
    { fact: "У волка есть клыки", isTrue: true },
    { fact: "У медведя есть когти", isTrue: true },
    { fact: "У кошки есть когти", isTrue: true },
    { fact: "У орла есть когти", isTrue: true },
    { fact: "У совы есть когти", isTrue: true },
    { fact: "У ястреба есть когти", isTrue: true },
    { fact: "У петуха есть шпоры", isTrue: true },
    { fact: "У лошади есть копыта", isTrue: true },
    { fact: "У коровы есть копыта", isTrue: true },
    { fact: "У овцы есть копыта", isTrue: true },
    { fact: "У козы есть рога", isTrue: true },
    { fact: "У коровы есть рога", isTrue: true },
    { fact: "У оленя есть рога", isTrue: true },
    { fact: "У лося есть рога", isTrue: true },
    { fact: "У барана есть рога", isTrue: true },
    { fact: "У носорога есть рог", isTrue: true },
    { fact: "У единорога есть рог", isTrue: false },
    { fact: "У зебры есть грива", isTrue: true },
    { fact: "У льва есть грива", isTrue: true },
    { fact: "У лошади есть грива", isTrue: true },
    { fact: "У тигра есть полоски", isTrue: true },
    { fact: "У леопарда есть пятна", isTrue: true },
    { fact: "У гепарда есть пятна", isTrue: true },
    { fact: "У жирафа есть пятна", isTrue: true },
    { fact: "У далматинца есть пятна", isTrue: true },
    { fact: "У коровы есть пятна", isTrue: true },
    { fact: "У божьей коровки есть пятнышки", isTrue: true },

    // ========== РАСТЕНИЯ И ЕДА (40 фактов) ==========
    { fact: "Банан — это ягода", isTrue: true },
    { fact: "Помидор — это овощ", isTrue: false },
    { fact: "Арбуз — это ягода", isTrue: true },
    { fact: "Клубника — это ягода", isTrue: false },
    { fact: "Мед — единственный продукт, который не портится", isTrue: true },
    { fact: "Морковь всегда была оранжевой", isTrue: false },
    { fact: "Яблоки тонут в воде", isTrue: false },
    { fact: "Шоколад полезен для собак", isTrue: false },
    { fact: "Арахис — это орех", isTrue: false },
    { fact: "Авокадо — это фрукт", isTrue: true },
    { fact: "Огурец — это фрукт", isTrue: true },
    { fact: "Картофель — это овощ", isTrue: true },
    { fact: "Лук заставляет плакать", isTrue: true },
    { fact: "Кофе делают из зёрен", isTrue: true },
    { fact: "Чай делают из листьев", isTrue: true },
    { fact: "Сыр делают из молока", isTrue: true },
    { fact: "Хлеб делают из муки", isTrue: true },
    { fact: "Виноград сушат, чтобы получить изюм", isTrue: true },
    { fact: "Мёд делают пчёлы", isTrue: true },
    { fact: "Лимон сладкий", isTrue: false },
    { fact: "Яблоко — это фрукт", isTrue: true },
    { fact: "Груша — это фрукт", isTrue: true },
    { fact: "Слива — это фрукт", isTrue: true },
    { fact: "Апельсин — это фрукт", isTrue: true },
    { fact: "Мандарин — это фрукт", isTrue: true },
    { fact: "Персик — это фрукт", isTrue: true },
    { fact: "Абрикос — это фрукт", isTrue: true },
    { fact: "Вишня — это ягода", isTrue: true },
    { fact: "Черешня — это ягода", isTrue: true },
    { fact: "Малина — это ягода", isTrue: true },
    { fact: "Смородина — это ягода", isTrue: true },
    { fact: "Крыжовник — это ягода", isTrue: true },
    { fact: "Голубика — это ягода", isTrue: true },
    { fact: "Черника — это ягода", isTrue: true },
    { fact: "Клюква — это ягода", isTrue: true },
    { fact: "Брусника — это ягода", isTrue: true },
    { fact: "Ежевика — это ягода", isTrue: true },
    { fact: "Виноград — это ягода", isTrue: true },
    { fact: "Свёкла — это овощ", isTrue: true },
    { fact: "Редис — это овощ", isTrue: true },
    { fact: "Тыква — это овощ", isTrue: true },
    { fact: "Кабачок — это овощ", isTrue: true },
    { fact: "Баклажан — это овощ", isTrue: true },
    { fact: "Перец — это овощ", isTrue: true },
    { fact: "Капуста — это овощ", isTrue: true },
    { fact: "Салат — это овощ", isTrue: true },
    { fact: "Шпинат — это овощ", isTrue: true },
    { fact: "Петрушка — это зелень", isTrue: true },
    { fact: "Укроп — это зелень", isTrue: true },
    { fact: "Чеснок — это овощ", isTrue: true },
    { fact: "Лук — это овощ", isTrue: true },

    // ========== ЧЕЛОВЕК И ТЕЛО (30 фактов) ==========
    { fact: "Человек может чихнуть с открытыми глазами", isTrue: false },
    { fact: "Сердце человека делает около 100 000 ударов в день", isTrue: true },
    { fact: "Мозг человека — самый большой орган", isTrue: false },
    { fact: "Человек дышит только одним носовым проходом за раз", isTrue: true },
    { fact: "Волосы человека растут даже после смерти", isTrue: false },
    { fact: "Человек моргает около 20 000 раз в день", isTrue: true },
    { fact: "Язык — самая сильная мышца в теле", isTrue: false },
    { fact: "Человек использует только 10% мозга", isTrue: false },
    { fact: "У человека есть зрение, слух, вкус, обоняние и осязание", isTrue: true },
    { fact: "Сердце находится слева", isTrue: false },
    { fact: "Человек растёт во сне", isTrue: true },
    { fact: "Уши продолжают расти всю жизнь", isTrue: true },
    { fact: "Человек не может дышать и глотать одновременно", isTrue: true },
    { fact: "Отпечатки пальцев у всех людей уникальны", isTrue: true },
    { fact: "Кожа — самый большой орган человека", isTrue: true },
    { fact: "У человека есть сердце", isTrue: true },
    { fact: "У человека есть мозг", isTrue: true },
    { fact: "У человека есть лёгкие", isTrue: true },
    { fact: "У человека есть желудок", isTrue: true },
    { fact: "У человека есть печень", isTrue: true },
    { fact: "У человека есть почки", isTrue: true },
    { fact: "У человека есть кости", isTrue: true },
    { fact: "У человека есть мышцы", isTrue: true },
    { fact: "У человека есть кожа", isTrue: true },
    { fact: "У человека есть волосы", isTrue: true },
    { fact: "У человека есть ногти", isTrue: true },
    { fact: "У человека есть зубы", isTrue: true },
    { fact: "У человека есть язык", isTrue: true },
    { fact: "У человека есть глаза", isTrue: true },
    { fact: "У человека есть уши", isTrue: true },

    // ========== ПРИРОДА И НАУКА (40 фактов) ==========
    { fact: "Земля вращается вокруг Солнца", isTrue: true },
    { fact: "Солнце — это звезда", isTrue: true },
    { fact: "Луна светит сама", isTrue: false },
    { fact: "Вода кипит при 100 градусах на уровне моря", isTrue: true },
    { fact: "Лёд тяжелее воды", isTrue: false },
    { fact: "Гром и молния происходят одновременно", isTrue: true },
    { fact: "Радуга имеет 7 цветов", isTrue: true },
    { fact: "Снег — это кристаллы льда", isTrue: true },
    { fact: "Облака состоят из капель воды", isTrue: true },
    { fact: "Горы растут", isTrue: true },
    { fact: "Реки текут только вниз", isTrue: true },
    { fact: "Океаны покрывают больше половины Земли", isTrue: true },
    { fact: "Земля — третья планета от Солнца", isTrue: true },
    { fact: "Венера — самая горячая планета", isTrue: true },
    { fact: "Сатурн имеет кольца", isTrue: true },
    { fact: "В космосе есть звук", isTrue: false },
    { fact: "Солнце больше Земли", isTrue: true },
    { fact: "Вода в море пресная", isTrue: false },
    { fact: "Земля — единственная планета с жизнью", isTrue: true },
    { fact: "Молния никогда не бьёт в одно место дважды", isTrue: false },
    { fact: "Днём светит солнце", isTrue: true },
    { fact: "Ночью светит луна", isTrue: true },
    { fact: "Звёзды видны ночью", isTrue: true },
    { fact: "Облака плывут по небу", isTrue: true },
    { fact: "Дождь падает с неба", isTrue: true },
    { fact: "Снег падает с неба", isTrue: true },
    { fact: "Град падает с неба", isTrue: true },
    { fact: "Ветер дует", isTrue: true },
    { fact: "Гром гремит", isTrue: true },
    { fact: "Молния сверкает", isTrue: true },
    { fact: "Радуга появляется после дождя", isTrue: true },
    { fact: "Туман стелется по земле", isTrue: true },
    { fact: "Иней появляется зимой", isTrue: true },
    { fact: "Роса появляется утром", isTrue: true },
    { fact: "Лёд скользкий", isTrue: true },
    { fact: "Снег белый", isTrue: true },
    { fact: "Трава зелёная", isTrue: true },
    { fact: "Небо голубое", isTrue: true },
    { fact: "Солнце жёлтое", isTrue: true },
    { fact: "Луна круглая", isTrue: true },

    // ========== СПОРТ И ИГРЫ (20 фактов) ==========
    { fact: "Футбол — самый популярный вид спорта в мире", isTrue: true },
    { fact: "Олимпийские игры проводятся каждый год", isTrue: false },
    { fact: "В футбольной команде 11 игроков", isTrue: true },
    { fact: "Баскетбол придумали в США", isTrue: true },
    { fact: "Шахматы — это спортивная игра", isTrue: true },
    { fact: "В хоккее играют клюшками", isTrue: true },
    { fact: "Теннисный мяч жёлтого цвета", isTrue: true },
    { fact: "Марафон — это бег на 42 километра", isTrue: true },
    { fact: "Плавание — олимпийский вид спорта", isTrue: true },
    { fact: "Волейбол играют руками", isTrue: true },
    { fact: "Футбол играют ногами", isTrue: true },
    { fact: "Баскетбол играют руками", isTrue: true },
    { fact: "В хоккей играют на льду", isTrue: true },
    { fact: "В теннис играют ракетками", isTrue: true },
    { fact: "В бадминтон играют ракетками", isTrue: true },
    { fact: "В шахматах есть король", isTrue: true },
    { fact: "В шахматах есть ферзь", isTrue: true },
    { fact: "В футболе есть вратарь", isTrue: true },
    { fact: "В хоккее есть вратарь", isTrue: true },
    { fact: "В баскетболе есть кольцо", isTrue: true },

    // ========== ТЕХНОЛОГИИ (10 фактов) ==========
    { fact: "Телефон изобрели в 19 веке", isTrue: true },
    { fact: "Компьютер — это машина для вычислений", isTrue: true },
    { fact: "Интернет появился в 20 веке", isTrue: true },
    { fact: "Роботы могут выполнять задания", isTrue: true },
    { fact: "Космонавты летают в космос на ракетах", isTrue: true },
    { fact: "Электрическую лампочку усовершенствовал Томас Эдисон", isTrue: true },
    { fact: "Телевизор изобрели раньше компьютера", isTrue: true },
    { fact: "Самолёт тяжелее воздуха", isTrue: true },
    { fact: "Машина ездит на бензине", isTrue: true },
    { fact: "Велосипед — это транспортное средство", isTrue: true }
];

console.log(`Всего фактов: ${FACTS.length}`);